import type { Cond, Effect, Op, PersonKind, StatKey } from '../engine/types';

// Atajos para escribir contenido de forma compacta.
export const c = {
  stat: (stat: StatKey, op: Op, value: number): Cond => ({ stat, op, value }),
  age: (min: number, max: number): Cond => ({ age: [min, max] }),
  year: (min: number, max: number): Cond => ({ year: [min, max] }),
  flag: (f: string): Cond => ({ flag: f }),
  noFlag: (f: string): Cond => ({ noFlag: f }),
  moneyGte: (n: number): Cond => ({ money: { gte: n } }),
  moneyLte: (n: number): Cond => ({ money: { lte: n } }),
  job: (): Cond => ({ job: true }),
  noJob: (): Cond => ({ job: false }),
  sector: (s: string): Cond => ({ sector: s }),
  edu: (n: number): Cond => ({ eduGte: n }),
  enrolled: (): Cond => ({ enrolled: true }),
  notEnrolled: (): Cond => ({ enrolled: false }),
  has: (k: PersonKind): Cond => ({ has: k }),
  hasNot: (k: PersonKind): Cond => ({ hasNot: k }),
  chance: (p: number): Cond => ({ chance: p }),
  jailed: (): Cond => ({ jailed: true }),
  free: (): Cond => ({ jailed: false }),
  /** Amistad con la persona objetivo. */
  tClose: (gte?: number, lte?: number): Cond => ({ targetFriendship: { gte, lte } }),
  /** Amor con la persona objetivo (bloqueado = no cumple). */
  tLove: (gte?: number, lte?: number): Cond => ({ targetRomance: { gte, lte } }),
  tAge: (gte?: number, lte?: number): Cond => ({ targetAge: { gte, lte } }),
  perf: (gte?: number, lte?: number): Cond => ({ performance: { gte, lte } }),
  wealth: (...n: number[]): Cond => ({ wealth: n }),
  married: (): Cond => ({ married: true }),
  trial: (): Cond => ({ trial: true }),
  asset: (k: 'house' | 'car'): Cond => ({ asset: k }),
  invested: (gte?: number, lte?: number): Cond => ({ invested: { gte, lte } }),
  loan: (): Cond => ({ loan: true }),
  single: (): Cond => ({ married: false }),
  tech: (t: string): Cond => ({ tech: t }),
  law: (l: string): Cond => ({ law: l }),
  noLaw: (l: string): Cond => ({ noLaw: l }),
  era: (e: string): Cond => ({ era: e }),
};

export const fx = {
  hap: (n: number): Effect => ({ stat: 'happiness', add: n }),
  hea: (n: number): Effect => ({ stat: 'health', add: n }),
  sma: (n: number): Effect => ({ stat: 'smarts', add: n }),
  loo: (n: number): Effect => ({ stat: 'looks', add: n }),
  money: (n: number): Effect => ({ money: n }),
  moneyPct: (n: number): Effect => ({ moneyPct: n }),
  flag: (f: string): Effect => ({ setFlag: f }),
  unflag: (f: string): Effect => ({ clearFlag: f }),
  add: (kind: PersonKind, age?: 'baby' | 'peer' | 'young'): Effect => ({ addPerson: { kind, age } }),
  /** Suma o resta amistad. */
  close: (who: 'target' | 'lover' | PersonKind, n: number): Effect => ({ relation: { who, friendship: n } }),
  /** Suma o resta amor (lo desbloquea si era positivo). */
  love: (who: 'target' | 'lover' | PersonKind, n: number): Effect => ({ relation: { who, romance: n } }),
  /** Cambia amistad y amor a la vez. */
  bond: (who: 'target' | 'lover' | PersonKind, friendship: number, romance: number): Effect => ({ relation: { who, friendship, romance } }),
  becomes: (who: 'target' | 'lover' | PersonKind, kind: PersonKind): Effect => ({
    relation: { who, becomes: kind },
  }),
  marry: (): Effect => ({ relation: { who: 'partner', married: true } }),
  perf: (n: number): Effect => ({ performance: n }),
  gpa: (n: number): Effect => ({ gpa: n }),
  raise: (mult: number): Effect => ({ salaryMult: mult }),
  fired: (): Effect => ({ loseJob: true }),
  jail: (min: number, max: number): Effect => ({ jail: [min, max] }),
  parole: (years: number): Effect => ({ parole: years }),
  arrest: (crime: string, min: number, max: number): Effect => ({ arrest: { crime, years: [min, max] } }),
  sentence: (s: 'full' | 'half' | 'double' | 'none' | 'probation'): Effect => ({ sentence: s }),
  loseAsset: (k: 'house' | 'car'): Effect => ({ loseAsset: k }),
  invest: (n: number): Effect => ({ invest: n }),
  remove: (who: 'target' | 'lover' | PersonKind): Effect => ({ relation: { who, remove: true } }),
  die: (cause: string): Effect => ({ die: cause }),
  log: (text: string): Effect => ({ log: text }),
  trigger: (id: string): Effect => ({ trigger: id }),
};
