import type { GameEvent } from '../../engine/types';
import { c, fx } from '../dsl';

export const CAREER: GameEvent[] = [
  { id: 'career.training', title: 'Curso de capacitación', tags: ['work'], weight: 9,
    conditions: [c.job(), c.age(20, 60), c.moneyGte(1500)],
    text: 'Te ofrecen hacer un curso de especialización que podría darte un impulso en tu carrera.',
    choices: [
      { label: 'Hacerlo ($1.500)', outcomes: [
        { weight: 7, text: 'Aprendiste un montón. {boss} tomó nota de tu iniciativa.', effects: [fx.money(-1500), fx.perf(14), fx.sma(2)] },
        { weight: 3, text: 'El curso era una estafa con certificado de colores.', effects: [fx.money(-1500), fx.hap(-2)] },
      ] },
      { label: 'Pasar', outcomes: [{ weight: 1, text: 'Dejaste pasar la oportunidad.', effects: [] }] },
    ] },
  { id: 'career.mentor', title: 'Un mentor', tags: ['work'], weight: 8,
    conditions: [c.job(), c.age(20, 55)],
    text: 'Un veterano de la empresa te tomó bajo su ala. Te enseña los atajos y los chismes.',
    effects: [fx.perf(10), fx.hap(3), fx.add('friend')] },
  { id: 'career.overtime', title: 'Horas extra', tags: ['work'], weight: 10,
    conditions: [c.job(), c.age(18, 62)],
    text: '{boss} te pide que te quedes hasta tarde todo el mes. "Es un momento clave para la empresa".',
    choices: [
      { label: 'Aceptar', outcomes: [
        { weight: 6, text: 'Te quedaste. Te pagaron algo extra y quedaste agotado/a.', effects: [fx.money(1800), fx.perf(8), fx.hap(-4), fx.hea(-2)] },
        { weight: 4, text: 'Te quedaste y nadie te lo agradeció. Ni te pagaron.', effects: [fx.perf(3), fx.hap(-6)] },
      ] },
      { label: 'Negarte', outcomes: [
        { weight: 6, text: '{boss} lo aceptó de mala gana.', effects: [fx.perf(-3)] },
        { weight: 4, text: '{boss} lo tomó como una falta de compromiso.', effects: [fx.perf(-10), fx.hap(-2)] },
      ] },
    ] },
  { id: 'career.strike', title: 'Huelga', tags: ['work'], weight: 6,
    conditions: [c.job(), c.age(20, 62), c.year(1950, 2300)],
    text: 'El sindicato convoca a una huelga por mejoras salariales.',
    choices: [
      { label: 'Adherir a la huelga', outcomes: [
        { weight: 5, text: 'La huelga ganó y se consiguió un aumento para todos.', effects: [fx.raise(1.1), fx.hap(4)] },
        { weight: 5, text: 'La huelga fracasó y descontaron los días.', effects: [fx.money(-1500), fx.hap(-3)] },
      ] },
      { label: 'Ir a trabajar', outcomes: [
        { weight: 1, text: 'Cruzaste el piquete. Tus compañeros no te lo perdonan.', effects: [fx.perf(5), fx.hap(-4)] },
      ] },
    ] },
  { id: 'career.reorg', title: 'Reestructuración', tags: ['work'], weight: 8,
    conditions: [c.job(), c.age(22, 62)],
    text: 'La empresa cambió toda la estructura. Nuevo jefe, nuevos objetivos, las mismas reuniones inútiles.',
    effects: [fx.perf(-6), fx.hap(-2)] },
  { id: 'career.malpractice', title: 'Error médico', tags: ['work'], weight: 6,
    conditions: [c.sector('salud'), c.job(), c.age(26, 65)],
    text: 'Un paciente te acusa de mala praxis. Te toca declarar ante el comité del hospital.',
    choices: [
      { label: 'Defender tu decisión', outcomes: [
        { weight: 6, text: 'Te dieron la razón. Todo fue un malentendido.', effects: [fx.perf(6), fx.hap(2)] },
        { weight: 4, text: 'Te sancionaron y pagaste una indemnización.', effects: [fx.perf(-15), fx.money(-6000), fx.hap(-8)] },
      ] },
      { label: 'Asumir el error', outcomes: [{ weight: 1, text: 'Asumiste el error con honestidad. Te sancionaron levemente.', effects: [fx.perf(-6), fx.hap(-3)] }] },
    ] },
  { id: 'career.big_case', title: 'La gran causa', tags: ['work'], weight: 6,
    conditions: [c.sector('legal'), c.job(), c.age(24, 65)],
    text: 'Te ofrecen un caso mediático que puede lanzarte a la fama… o hundirte.',
    choices: [
      { label: 'Aceptarlo', outcomes: [
        { weight: 5, text: 'Ganaste el juicio del año. Todos quieren tus servicios.', effects: [fx.raise(1.3), fx.hap(8), fx.perf(15)] },
        { weight: 5, text: 'Perdiste y quedaste como un aficionado.', effects: [fx.perf(-15), fx.hap(-6)] },
      ] },
      { label: 'Declinar', outcomes: [{ weight: 1, text: 'Lo declinaste. Sos prudente, pero nadie escribe libros de eso.', effects: [] }] },
    ] },
  { id: 'career.tech_layoffs', title: 'Despidos masivos en tecnología', tags: ['work'], weight: 6,
    conditions: [c.sector('tecnología'), c.job(), c.year(2001, 2300)],
    text: 'Tu empresa despidió a un tercio del personal por "optimización".',
    choices: [
      { label: 'Sobrevivir y agachar la cabeza', outcomes: [
        { weight: 5, text: 'Sobreviviste al recorte. Tenés el doble de trabajo.', effects: [fx.perf(4), fx.hap(-4)] },
        { weight: 5, text: 'Te tocó a vos. Un mail y tu acceso, desactivado.', effects: [fx.fired(), fx.money(3000), fx.hap(-8)] },
      ] },
    ] },
  { id: 'career.startup', title: 'Oferta de una startup', tags: ['work'], weight: 5,
    conditions: [c.sector('tecnología'), c.job(), c.age(22, 50)],
    text: 'Unos amigos te ofrecen sumarte a su startup: poco sueldo, muchas acciones.',
    choices: [
      { label: 'Arriesgarse', outcomes: [
        { weight: 1, text: 'La startup fue adquirida por una multinacional. Sos millonario/a.', effects: [fx.money(250000), fx.hap(15)] },
        { weight: 6, text: 'La startup quebró en un año. Volvés a buscar trabajo.', effects: [fx.fired(), fx.hap(-6), fx.money(-3000)] },
        { weight: 3, text: 'Sobrevivió, pero tus acciones valen poco. Volvés a tu empleo.', effects: [fx.hap(1)] },
      ] },
      { label: 'Quedarte donde estás', outcomes: [{ weight: 1, text: 'No te arriesgaste. La comodidad tiene sus ventajas.', effects: [] }] },
    ] },
  { id: 'career.grateful_student', title: 'Un alumno agradecido', tags: ['work'], weight: 8,
    conditions: [c.sector('educación'), c.job()],
    text: 'Un ex alumno te encontró para agradecerte: "Usted me cambió la vida". Lloraste en el subte.',
    effects: [fx.hap(8), fx.perf(3)] },
  { id: 'career.tip_jackpot', title: 'Una propina enorme', tags: ['work'], weight: 8,
    conditions: [c.sector('gastronomía'), c.job()],
    text: 'Un cliente muy generoso te dejó una propina que equivale a una semana de sueldo.',
    effects: [fx.money(1500), fx.hap(5)] },
  { id: 'career.work_accident', title: 'Accidente laboral', tags: ['work'], weight: 8,
    conditions: [c.sector('obra'), c.job()],
    text: 'Te cayó una viga en la obra. Fue un susto grande y un dolor peor.',
    effects: [fx.hea(-14), fx.money(2500), fx.hap(-4)] },
  { id: 'career.big_deal', title: 'Cerraste un gran negocio', tags: ['work'], weight: 8,
    conditions: [c.sector('ventas'), c.job(), c.perf(50)],
    text: 'Cerraste la venta más grande del año. {boss} te dio una palmada en la espalda y una comisión.',
    effects: [fx.money(4000), fx.perf(10), fx.hap(5)] },
  { id: 'career.audit_pressure', title: 'Presión por los números', tags: ['work', 'crime'], weight: 5,
    conditions: [c.sector('finanzas'), c.job()],
    text: '{boss} te pide "acomodar" unos números antes de la auditoría.',
    choices: [
      { label: 'Hacerlo', outcomes: [
        { weight: 6, text: 'Acomodaste los números. Nadie se dio cuenta. Por ahora.', effects: [fx.money(3000), fx.perf(8), fx.hap(-3)] },
        { weight: 4, text: 'La auditoría lo detectó. Terminaste imputado.', effects: [fx.fired(), fx.arrest('falsificación contable', 1, 5), fx.hap(-10)] },
      ] },
      { label: 'Negarte', outcomes: [
        { weight: 5, text: '{boss} lo aceptó y te tuvo en cuenta.', effects: [fx.perf(5), fx.hap(2)] },
        { weight: 5, text: '{boss} te empezó a hacer la vida imposible.', effects: [fx.perf(-12), fx.hap(-4)] },
      ] },
    ] },
  { id: 'career.dream_job', title: 'Trabajo soñado', tags: ['work'], weight: 3,
    conditions: [c.job(), c.perf(85), c.age(25, 55)],
    text: 'Una empresa importante te contacta con una oferta que no podés rechazar.',
    effects: [fx.raise(1.4), fx.hap(10), fx.perf(-10)] },
];

export const MONEY_EXTRA: GameEvent[] = [
  { id: 'money.house_repairs', title: 'Arreglos en casa', tags: ['money'], weight: 12,
    conditions: [c.asset('house'), c.moneyGte(1000)],
    text: 'Se vino abajo una parte del techo de tu casa. Tener casa propia también es tener problemas propios.',
    effects: [fx.money(-3000), fx.hap(-3)] },
  { id: 'money.car_crash', title: 'Choque', tags: ['money'], weight: 8,
    conditions: [c.asset('car')],
    text: 'Chocaste en una esquina. Nadie salió lastimado, salvo el paragolpes y tu bolsillo.',
    effects: [fx.money(-2500), fx.hea(-4), fx.hap(-4)] },
  { id: 'money.car_stolen', title: 'Te robaron el auto', tags: ['money'], weight: 4,
    conditions: [c.asset('car')],
    text: 'Fuiste a buscar el auto donde lo habías dejado y solo había un charco de aceite.',
    effects: [fx.loseAsset('car'), fx.hap(-8)] },
  { id: 'money.house_boom', title: 'Boom inmobiliario', tags: ['money'], weight: 5,
    conditions: [c.asset('house')],
    text: 'Tu barrio se puso de moda. Todos los vecinos hablan del precio de sus casas y tienen razón en alegrarse.',
    effects: [fx.hap(4), fx.money(1000)] },
  { id: 'money.stock_tip', title: 'Un dato de la bolsa', tags: ['money'], weight: 7,
    conditions: [c.age(20, 80), c.moneyGte(6000)],
    text: 'Un conocido te pasa un "dato" infalible de la bolsa. Necesita que le entres con $5.000.',
    choices: [
      { label: 'Invertir', outcomes: [
        { weight: 4, text: 'Fue un buen dato. Tus $5.000 quedaron invertidos y ya subieron.', effects: [fx.invest(6500)] },
        { weight: 6, text: 'El dato era una estafa piramidal. Perdiste todo.', effects: [fx.money(-5000), fx.hap(-6)] },
      ] },
      { label: 'Ignorarlo', outcomes: [{ weight: 1, text: 'Lo ignoraste. El dato salió bien, para variar.', effects: [fx.hap(-1)] }] },
    ] },
  { id: 'money.startup_invest', title: 'Un amigo emprendedor', tags: ['money'], weight: 6,
    conditions: [c.has('friend'), c.age(22, 65), c.moneyGte(6000)],
    text: '{friend} te pide $5.000 para abrir una cafetería "diferente".',
    choices: [
      { label: 'Invertir', outcomes: [
        { weight: 3, text: 'La cafetería explotó de éxito. Te devolvió el triple.', effects: [fx.money(15000), fx.close('friend', 12), fx.hap(6)] },
        { weight: 7, text: 'Cerró a los seis meses. Perdiste tu plata y probablemente al amigo.', effects: [fx.money(-5000), fx.close('friend', -15), fx.hap(-4)] },
      ] },
      { label: 'Decir que no', outcomes: [{ weight: 1, text: 'Le dijiste que no. Abrió igual. Le va bien.', effects: [fx.hap(-1)] }] },
    ] },
  { id: 'money.side_gig', title: 'Un trabajito extra', tags: ['money'], weight: 9,
    conditions: [c.age(18, 70)],
    text: 'Te salió un laburo extra en tus tiempos libres. No es mucho, pero suma.',
    effects: [fx.money(1800), fx.hap(1)] },
  { id: 'money.charity', title: 'Una causa noble', tags: ['money'], weight: 6,
    conditions: [c.age(20, 90), c.moneyGte(3000)],
    text: 'Una campaña de ayuda a chicos de un barrio necesitado te conmueve.',
    choices: [
      { label: 'Donar $1.000', outcomes: [{ weight: 1, text: 'Donaste. Te sentiste bien y tus amigos lo notaron.', effects: [fx.money(-1000), fx.hap(6)] }] },
      { label: 'Pasar', outcomes: [{ weight: 1, text: 'Pasaste de largo. Nadie te juzgó, salvo vos.', effects: [fx.hap(-1)] }] },
    ] },
  { id: 'money.bank_calls', title: 'El banco llama', tags: ['money'], weight: 9,
    conditions: [c.loan(), c.moneyLte(1000)],
    text: 'El banco te llamó por tu préstamo. Tres veces. Un día.',
    effects: [fx.hap(-4)] },
];
