import type { GameEvent } from '../../engine/types';
import { c, fx } from '../dsl';

export const CHILDHOOD: GameEvent[] = [
  { id: 'child.first_words', title: 'Primeras palabras', tags: ['child'], once: true, weight: 40,
    conditions: [c.age(1, 2)],
    text: 'Dijiste tu primera palabra. Tus padres juran que fue "mamá". Vos sabés que fue "no".',
    effects: [fx.hap(3)] },
  { id: 'child.walking', title: 'Primeros pasos', tags: ['child'], once: true, weight: 40,
    conditions: [c.age(1, 2)],
    text: 'Empezaste a caminar. Y a destruir la casa con más eficiencia.',
    effects: [fx.hap(3), fx.hea(1)] },
  { id: 'child.fear_dark', title: 'Miedo a la oscuridad', tags: ['child'], weight: 12, once: true,
    conditions: [c.age(3, 8)],
    text: 'Te convenciste de que hay algo debajo de la cama. Dormiste con la luz prendida por meses.',
    effects: [fx.hap(-2)] },
  { id: 'child.imaginary_friend', title: 'Amigo imaginario', tags: ['child'], weight: 10, once: true,
    conditions: [c.age(3, 7)],
    text: 'Tenías un amigo imaginario que siempre te metía en problemas. Nunca pudiste probar que no fue él.',
    effects: [fx.sma(2), fx.hap(2)] },
  { id: 'child.first_day', title: 'Primer día de clases', tags: ['child', 'school'], weight: 60, once: true,
    conditions: [c.age(5, 6)],
    text: 'Primer día de escuela. Lloraste en la puerta. Tu mamá también.',
    effects: [fx.hap(-1), fx.add('friend', 'peer')] },
  { id: 'child.make_friend', title: 'Un nuevo amigo', tags: ['child', 'school'], weight: 14,
    conditions: [c.age(6, 11), c.hasNot('friend')],
    text: 'Compartiste la merienda con un nene/a que estaba solo/a. Desde entonces son inseparables.',
    effects: [fx.add('friend', 'peer'), fx.hap(4)] },
  { id: 'child.bully', title: 'Matón de la escuela', tags: ['child', 'school'], weight: 14,
    conditions: [c.age(6, 12), c.enrolled()],
    text: 'Un chico más grande te molesta todos los días en el recreo.',
    choices: [
      { label: 'Defenderte a las piñas', outcomes: [
        { weight: 5, text: 'Le diste un buen golpe. Nadie se metió más con vos.', effects: [fx.hap(4), fx.hea(-2)] },
        { weight: 5, text: 'Te dio una paliza, pero se lo pensó dos veces antes de volver a molestarte.', effects: [fx.hap(-3), fx.hea(-5)] },
      ] },
      { label: 'Avisarle a la maestra', outcomes: [
        { weight: 6, text: 'La maestra intervino y todo se calmó. Te dijeron alcahuete.', effects: [fx.hap(-1)] },
        { weight: 4, text: 'No hizo nada. Te dijo que "son cosas de chicos".', effects: [fx.hap(-5)] },
      ] },
      { label: 'Aguantarte en silencio', outcomes: [
        { weight: 1, text: 'Sufriste en silencio todo el año. No es sano, pero es una tradición.', effects: [fx.hap(-8)] },
      ] },
    ] },
  { id: 'child.pet', title: 'Un perrito', tags: ['child'], weight: 8, once: true,
    conditions: [c.age(5, 11), c.noFlag('pet')],
    text: 'Tus padres, contra toda predicción, te regalaron un perro. Le pusiste un nombre ridículo y lo amás con locura.',
    effects: [fx.hap(9), fx.flag('pet')] },
  { id: 'child.stole_candy', title: 'Caramelos robados', tags: ['child'], weight: 10,
    conditions: [c.age(6, 11)],
    text: 'Te metiste caramelos en el bolsillo en el kiosco. Tu mamá los encontró.',
    choices: [
      { label: 'Confesar', outcomes: [
        { weight: 1, text: 'Confesaste. Te obligaron a devolverlos y pedir perdón. Humillante, pero honesto.', effects: [fx.hap(-2), fx.close('mother', 2)] },
      ] },
      { label: 'Negar todo', outcomes: [
        { weight: 6, text: 'Dijiste que te los dio un amigo. Te creyeron.', effects: [fx.hap(2)] },
        { weight: 4, text: 'No colaron. Castigo y sin postre por dos semanas.', effects: [fx.hap(-4), fx.close('mother', -4)] },
      ] },
    ] },
  { id: 'child.broken_arm', title: 'Un brazo roto', tags: ['child', 'health'], weight: 8,
    conditions: [c.age(4, 12)],
    text: 'Te caíste de un árbol intentando demostrar algo que nadie te pidió. Yeso por dos meses.',
    effects: [fx.hea(-6), fx.hap(-2)] },
  { id: 'child.parents_fight', title: 'Peleas en casa', tags: ['child', 'family'], weight: 9,
    conditions: [c.age(4, 14), c.has('mother'), c.has('father')],
    text: 'Tus padres discuten a los gritos casi todas las noches. Te tapás los oídos con la almohada.',
    effects: [fx.hap(-5)] },
  { id: 'child.gifted', title: 'Nene/a prodigio', tags: ['child', 'school'], weight: 12, once: true,
    conditions: [c.age(6, 11), c.stat('smarts', '>=', 75)],
    text: 'La maestra les dijo a tus padres que sos un/a chico/a excepcional. Te dieron ganas de llorar y de ser mediocre a la vez.',
    effects: [fx.sma(3), fx.hap(3)] },
  { id: 'child.sibling_born', title: 'Un nuevo hermanito', tags: ['child', 'family'], weight: 6, once: true,
    conditions: [c.age(2, 10), c.has('mother'), c.has('father')],
    text: 'Tus padres trajeron un bebé a casa. Ahora la atención no es solo tuya.',
    effects: [fx.add('sibling', 'baby'), fx.hap(-1)] },
  { id: 'child.grandparent_dies', title: 'Adiós, abuelo/a', tags: ['child', 'family'], weight: 6, once: true,
    conditions: [c.age(5, 15)],
    text: 'Se murió tu abuelo/a. Fue tu primera vez en un velorio. Nadie te explicó bien qué estaba pasando.',
    effects: [fx.hap(-6)] },
  { id: 'child.school_play', title: 'Acto escolar', tags: ['child', 'school'], weight: 10,
    conditions: [c.age(6, 11), c.enrolled()],
    text: 'La maestra te eligió para un papel en el acto escolar.',
    choices: [
      { label: 'Actuar con todo', outcomes: [
        { weight: 6, text: 'Sacaste aplausos. Tus padres lloraron de la emoción.', effects: [fx.hap(6), fx.loo(1)] },
        { weight: 4, text: 'Te olvidaste el texto y te quedaste congelado/a frente a 200 personas. Trauma de por vida.', effects: [fx.hap(-6)] },
      ] },
      { label: 'Fingir que estás enfermo/a', outcomes: [
        { weight: 1, text: 'Zafaste del acto. Tu compañero/a tuvo que reemplazarte y fue un éxito, para tu envidia.', effects: [fx.hap(-1)] },
      ] },
    ] },
  { id: 'child.flu', title: 'Gripe fuerte', tags: ['child', 'health'], weight: 12,
    conditions: [c.age(0, 12)],
    text: 'Pasaste una semana en cama con fiebre. Tu mamá te llenó de sopa y mimos.',
    effects: [fx.hea(-4), fx.close('mother', 2)] },
  { id: 'child.lucky_toy', title: 'El regalo perfecto', tags: ['child'], weight: 8,
    conditions: [c.age(3, 11)],
    text: 'Para tu cumpleaños te regalaron exactamente lo que querías. Fue el mejor día del año.',
    effects: [fx.hap(6)] },
  { id: 'child.moved', title: 'Mudanza', tags: ['child', 'family'], weight: 6, once: true,
    conditions: [c.age(5, 14)],
    text: 'Tus padres decidieron mudarse a otro barrio. Dejaste amigos y aprendiste a empezar de cero.',
    effects: [fx.hap(-4), fx.add('friend', 'peer')] },
];
