import type { GameEvent } from '../../engine/types';
import { c, fx } from '../dsl';

// ── Eventos históricos (país genérico): siempre se disparan al llegar su año ──
export const HISTORICAL: GameEvent[] = [
  { id: 'hist.coup_1976', title: 'Golpe de Estado', tags: ['historical'], weight: 1000, once: true,
    conditions: [c.year(1976, 1976)],
    text: 'Un golpe militar derrocó al gobierno. Toque de queda, censura y miedo en las calles.',
    effects: [fx.hap(-7), fx.hea(-2)] },
  { id: 'hist.crisis_1982', title: 'Crisis de la deuda', tags: ['historical'], weight: 1000, once: true,
    conditions: [c.year(1982, 1982)],
    text: 'Estalló la crisis de la deuda. Los precios se dispararon y la moneda se derrumbó.',
    effects: [fx.moneyPct(-0.18), fx.hap(-5)] },
  { id: 'hist.hyperinflation_1989', title: 'Hiperinflación', tags: ['historical'], weight: 1000, once: true,
    conditions: [c.year(1989, 1989)],
    text: 'Los precios cambian dos veces por día. Los ahorros se evaporan en semanas.',
    effects: [fx.moneyPct(-0.35), fx.hap(-8)] },
  { id: 'hist.internet_1998', title: 'Llegó internet', tags: ['historical'], weight: 1000, once: true,
    conditions: [c.year(1998, 1998)],
    text: 'Toda la gente habla de internet. Tu casa se llena de cables y del ruido del módem.',
    effects: [fx.sma(2), fx.hap(2)] },
  { id: 'hist.crisis_2001', title: 'Crisis económica', tags: ['historical'], weight: 1000, once: true,
    conditions: [c.year(2001, 2001)],
    text: 'Se congelaron los depósitos bancarios y hubo protestas masivas. Muchos perdieron gran parte de sus ahorros.',
    effects: [fx.moneyPct(-0.3), fx.hap(-8)] },
  { id: 'hist.smartphones_2008', title: 'Crisis global y smartphones', tags: ['historical'], weight: 1000, once: true,
    conditions: [c.year(2008, 2008)],
    text: 'Una crisis financiera mundial sacudió los mercados. Al mismo tiempo, todos empezaron a mirar pantallas táctiles.',
    effects: [fx.moneyPct(-0.1), fx.hap(-3)] },
  { id: 'hist.blackout_2015', title: 'Gran apagón', tags: ['historical'], weight: 1000, once: true,
    conditions: [c.year(2015, 2015)],
    text: 'Hubo un apagón que duró tres días. Se rompieron las heladeras y la paciencia de todo el barrio.',
    effects: [fx.hap(-3), fx.money(-300)] },
  { id: 'hist.ai_2023', title: 'La era de la IA', tags: ['historical'], weight: 1000, once: true,
    conditions: [c.year(2023, 2023)],
    text: 'Las inteligencias artificiales se metieron en todos lados. Algunos las aman. Otros están con miedo por sus trabajos.',
    effects: [fx.sma(1)] },
];

export const RANDOM: GameEvent[] = [
  { id: 'random.free_trip', title: 'Un viaje inesperado', tags: ['random'], weight: 5,
    conditions: [c.age(18, 80)],
    text: 'Un amigo te ofrece un lugar en un viaje que ya tiene todo pago, a último minuto.',
    choices: [
      { label: 'Irte de viaje', outcomes: [
        { weight: 7, text: 'Fue el mejor viaje de tu vida. Volviste con fotos, historias y un bronceado dudoso.', effects: [fx.hap(9), fx.money(-400)] },
        { weight: 3, text: 'Se arruinó todo: perdieron las valijas y se pelearon con el conductor.', effects: [fx.hap(-2), fx.money(-800)] },
      ] },
      { label: 'Quedarte', outcomes: [{ weight: 1, text: 'Te quedaste. Tus amigos volvieron con historias que te van a contar mil veces.', effects: [fx.hap(-2)] }] },
    ] },
  { id: 'random.viral_video', title: 'Video viral', tags: ['random', 'tech'], weight: 4,
    conditions: [c.year(2010, 2200), c.age(12, 70)],
    text: 'Alguien te filmó haciendo algo ridículo y el video llegó a un millón de vistas.',
    effects: [fx.hap(-3), fx.loo(-1), fx.money(500)] },
  { id: 'random.old_friend', title: 'Viejo amigo', tags: ['random'], weight: 8,
    conditions: [c.age(25, 90)],
    text: 'Te cruzaste con un compañero de la escuela que no veías hace veinte años. Se pusieron al día.',
    effects: [fx.add('friend'), fx.hap(4)] },
  { id: 'random.cult', title: 'Una comunidad "especial"', tags: ['random'], weight: 4,
    conditions: [c.age(18, 60), c.stat('happiness', '<=', 50)],
    text: 'Una persona muy amable te invita a un retiro espiritual "para reconectar con vos mismo/a".',
    choices: [
      { label: 'Ir al retiro', outcomes: [
        { weight: 5, text: 'Fue un fin de semana de yoga, sopa y calma. Salió relativamente bien.', effects: [fx.hap(5), fx.money(-600)] },
        { weight: 5, text: 'Resultó ser una secta. Les diste casi todo lo que tenías antes de poder escaparte.', effects: [fx.hap(-8), fx.money(-7000)] },
      ] },
      { label: 'Rechazar', outcomes: [{ weight: 1, text: 'Dijiste que no. Tu intuición de supervivencia funcionó.', effects: [fx.hap(1)] }] },
    ] },
  { id: 'random.noisy_neighbor', title: 'Vecino ruidoso', tags: ['random'], weight: 10,
    conditions: [c.age(18, 95)],
    text: 'Tu vecino hace fiestas hasta las 5 de la mañana los martes. No dormís.',
    effects: [fx.hap(-4), fx.hea(-1)] },
  { id: 'random.mysterious_letter', title: 'Una carta misteriosa', tags: ['random'], weight: 4,
    conditions: [c.age(16, 90)],
    text: 'Llegó una carta sin remitente que dice: "Sé lo que hiciste". No tenés idea a qué se refiere. O sí.',
    choices: [
      { label: 'Ignorarla', outcomes: [
        { weight: 8, text: 'Nunca volvió a pasar. Todavía a veces te da escalofríos.', effects: [fx.hap(-1)] },
        { weight: 2, text: 'Una semana después te llegó otra. Esta vez con una foto tuya.', effects: [fx.hap(-6)] },
      ] },
      { label: 'Investigarla', outcomes: [
        { weight: 1, text: 'Era una broma de un amigo. Le respondiste con una peor.', effects: [fx.hap(3)] },
      ] },
    ] },
  { id: 'random.dream_job_meme', title: 'Un golpe de suerte', tags: ['random'], weight: 5,
    conditions: [c.age(18, 70)],
    text: 'Por una casualidad, alguien se acordó de vos y te pasó una recomendación que te abrió una puerta.',
    effects: [fx.hap(4), fx.money(1500)] },
  { id: 'random.moved_city', title: 'Mudanza', tags: ['random'], weight: 6,
    conditions: [c.age(20, 60)],
    text: 'Te surgió la posibilidad de mudarte a otra ciudad para empezar de cero.',
    choices: [
      { label: 'Mudarte', outcomes: [
        { weight: 6, text: 'Empezaste de nuevo. La ciudad te trató bien.', effects: [fx.hap(6), fx.money(-1500), fx.add('friend')] },
        { weight: 4, text: 'Te sentiste solo/a durante meses, extrañando todo.', effects: [fx.hap(-5), fx.money(-1500)] },
      ] },
      { label: 'Quedarte', outcomes: [{ weight: 1, text: 'Te quedaste. La comodidad pesó más.', effects: [] }] },
    ] },
  { id: 'random.identity_crisis', title: 'Duda existencial', tags: ['random'], weight: 8, cooldown: 10,
    conditions: [c.age(20, 90)],
    text: 'De madrugada te preguntaste para qué hacés todo lo que hacés. No encontraste respuesta. Dormiste mal.',
    effects: [fx.hap(-3)] },
  { id: 'random.small_joy', title: 'Un día perfecto', tags: ['random'], weight: 12, cooldown: 12,
    conditions: [c.age(6, 99)],
    text: 'Sin razón aparente, tuviste un día perfecto. Sol, música y comida rica. No pasó nada más, y estuvo genial.',
    effects: [fx.hap(5)] },
  { id: 'random.pet_dies', title: 'Adiós, compañero', tags: ['random'], weight: 12, once: true,
    conditions: [c.flag('pet'), c.age(12, 99)],
    text: 'Tu mascota murió después de muchos años. Lloraste como no lo habías hecho en mucho tiempo.',
    effects: [fx.hap(-9), fx.unflag('pet')] },
  { id: 'random.scholarship', title: 'Beca', tags: ['random', 'school'], weight: 7,
    conditions: [c.age(17, 30), c.stat('smarts', '>=', 70)],
    text: 'Te ofrecieron una beca por tus notas. El sistema, por una vez, funcionó.',
    effects: [fx.money(3000), fx.hap(5), fx.sma(1)] },
];

// ── Vejez ──
export const OLD: GameEvent[] = [
  { id: 'old.lonely', title: 'Soledad', tags: ['old'], weight: 14,
    conditions: [c.age(65, 110), c.hasNot('partner')],
    text: 'La casa está muy silenciosa. Los años se hacen largos cuando no hay nadie para compartir un mate.',
    effects: [fx.hap(-5)] },
  { id: 'old.memory', title: 'Memoria', tags: ['old'], weight: 10,
    conditions: [c.age(70, 110)],
    text: 'Empezaste a olvidar dónde dejás las llaves. Y los nombres. Y, a veces, qué ibas a decir.',
    effects: [fx.sma(-4), fx.hap(-3)] },
  { id: 'old.fall', title: 'Una caída', tags: ['old', 'health'], weight: 10,
    conditions: [c.age(70, 110)],
    text: 'Te caíste en el baño y no podías levantarte. Un vecino te encontró horas después.',
    effects: [fx.hea(-12), fx.hap(-4)] },
  { id: 'old.bucket_list', title: 'Lista de deseos', tags: ['old'], weight: 8,
    conditions: [c.age(60, 95), c.moneyGte(3000)],
    text: 'Te dieron ganas de cumplir el último deseo pendiente de tu vida.',
    choices: [
      { label: 'Hacerlo', outcomes: [
        { weight: 1, text: 'Cumpliste el deseo. Valió cada peso.', effects: [fx.money(-3000), fx.hap(12)] },
      ] },
      { label: 'Guardar la plata', outcomes: [{ weight: 1, text: 'Preferiste el ahorro. La seguridad tiene su encanto.', effects: [fx.hap(-1)] }] },
    ] },
  { id: 'old.retirement_joy', title: 'Días tranquilos', tags: ['old'], weight: 12,
    conditions: [c.flag('retired'), c.stat('health', '>=', 40)],
    text: 'Pasás las mañanas tomando mate en la plaza y las tardes dormitando frente a la tele. No está mal.',
    effects: [fx.hap(4)] },
  { id: 'old.reminisce', title: 'Recuerdos', tags: ['old'], weight: 8,
    conditions: [c.age(70, 110)],
    text: 'Te encontraste unas fotos viejas y pasaste la tarde recordando. Reíste, lloraste, y te preguntaste cuánto queda.',
    effects: [fx.hap(2)] },
];
