import type { GameEvent } from '../../engine/types';
import { c, fx } from '../dsl';

// Eventos con una persona específica: {target} es esa persona.
export const RELATIONSHIPS: GameEvent[] = [
  { id: 'rel.friend_help', title: 'Un amigo necesita ayuda', tags: ['rel'], target: 'friend', weight: 10,
    conditions: [c.age(16, 90)],
    text: '{target} te llamó a las 2 de la mañana: se quedó tirado con el auto y no tiene a nadie más.',
    choices: [
      { label: 'Ir a buscarlo/a', outcomes: [
        { weight: 1, text: 'Fuiste corriendo. {target} nunca lo va a olvidar.', effects: [fx.close('target', 14), fx.hap(2), fx.hea(-1)] },
      ] },
      { label: 'Decirle que se arregle solo/a', outcomes: [
        { weight: 1, text: 'Cortaste el teléfono. {target} no volvió a llamar por un tiempo.', effects: [fx.close('target', -15)] },
      ] },
    ] },
  { id: 'rel.friend_wedding', title: 'Casamiento', tags: ['rel'], target: 'friend', weight: 7,
    conditions: [c.age(22, 50)],
    text: '{target} se casa. La fiesta fue excelente, el vestido feo y el discurso del padrino eterno.',
    effects: [fx.close('target', 8), fx.hap(4), fx.money(-300)] },
  { id: 'rel.friend_conflict', title: 'Malentendido', tags: ['rel'], target: 'friend', weight: 8,
    conditions: [c.age(14, 90)],
    text: '{target} se enteró de algo que dijiste a sus espaldas. Está muy enojado/a.',
    choices: [
      { label: 'Pedir disculpas', outcomes: [
        { weight: 6, text: '{target} aceptó tus disculpas. Se abrazaron.', effects: [fx.close('target', 5)] },
        { weight: 4, text: '{target} no quiere saber nada por ahora.', effects: [fx.close('target', -10), fx.hap(-2)] },
      ] },
      { label: 'Negar todo', outcomes: [
        { weight: 3, text: '{target} te creyó. Zafaste.', effects: [] },
        { weight: 7, text: '{target} tenía pruebas. La amistad se rompió.', effects: [fx.close('target', -35), fx.hap(-5)] },
      ] },
    ] },
  { id: 'rel.friend_moves', title: 'Se fue', tags: ['rel'], target: 'friend', weight: 6,
    conditions: [c.age(18, 70)],
    text: '{target} se mudó a otro país por trabajo. Se prometieron hablar todos los días. Ya sabés cómo sigue.',
    effects: [fx.close('target', -25), fx.hap(-3)] },
  { id: 'rel.friend_bail', title: 'Problemas con la ley', tags: ['rel'], target: 'friend', weight: 5,
    conditions: [c.age(18, 60), c.moneyGte(2000)],
    text: '{target} está detenido y necesita $2.000 para la fianza.',
    choices: [
      { label: 'Pagar la fianza', outcomes: [
        { weight: 7, text: '{target} salió y te lo agradeció con lágrimas en los ojos.', effects: [fx.money(-2000), fx.close('target', 20)] },
        { weight: 3, text: '{target} desapareció después de salir. La fianza se perdió.', effects: [fx.money(-2000), fx.close('target', -20), fx.hap(-4)] },
      ] },
      { label: 'Dejarlo/a ahí', outcomes: [{ weight: 1, text: 'No pusiste un peso. {target} lo vive como una traición.', effects: [fx.close('target', -30)] }] },
    ] },
  { id: 'rel.friend_success', title: 'A {target} le va mejor', tags: ['rel'], target: 'friend', weight: 6,
    conditions: [c.age(22, 70)],
    text: '{target} consiguió un ascenso enorme y no para de hablar de eso. Te da una mezcla de orgullo y envidia.',
    effects: [fx.hap(-2), fx.close('target', 2)] },
  { id: 'rel.partner_jealous', title: 'Celos', tags: ['rel'], target: 'partner', weight: 8,
    conditions: [c.age(16, 80)],
    text: '{target} revisó tu celular y armó una escena. Tenés que explicar quién es esa persona.',
    choices: [
      { label: 'Explicar con calma', outcomes: [
        { weight: 6, text: '{target} entendió. Hasta pidió disculpas.', effects: [fx.close('target', 4)] },
        { weight: 4, text: 'Nada de lo que dijiste alcanzó. Discutieron toda la noche.', effects: [fx.close('target', -10), fx.hap(-3)] },
      ] },
      { label: 'Contraatacar', outcomes: [
        { weight: 1, text: 'La pelea escaló y volaron platos.', effects: [fx.close('target', -20), fx.hap(-5)] },
      ] },
    ] },
  { id: 'rel.partner_promotion', title: 'Buena noticia', tags: ['rel'], target: 'partner', weight: 6,
    conditions: [c.age(22, 60)],
    text: '{target} recibió un ascenso. Festejaron con una cena y mucho vino.',
    effects: [fx.money(2500), fx.close('target', 5), fx.hap(4)] },
  { id: 'rel.partner_illness', title: 'La salud de {target}', tags: ['rel'], target: 'partner', weight: 5,
    conditions: [c.age(40, 95)],
    text: '{target} se enfermó y tuviste que hacerte cargo de todo. Es agotador, pero los unió.',
    effects: [fx.hap(-5), fx.money(-1500), fx.close('target', 10)] },
  { id: 'rel.partner_surprise', title: 'Sorpresa', tags: ['rel'], target: 'partner', weight: 8,
    conditions: [c.age(16, 90)],
    text: '{target} te preparó una sorpresa: cena, velas y hasta limpió la casa. Sospechoso, pero lindo.',
    effects: [fx.close('target', 8), fx.hap(5)] },
  { id: 'rel.partner_debt', title: 'Deuda escondida', tags: ['rel'], target: 'partner', weight: 5,
    conditions: [c.age(22, 70), c.moneyGte(3000)],
    text: 'Te enterás de que {target} tiene deudas que nunca te contó. Son $3.000.',
    choices: [
      { label: 'Pagarlas', outcomes: [{ weight: 1, text: 'Pagaste la deuda. {target} prometió no volver a esconderte nada.', effects: [fx.money(-3000), fx.close('target', 10)] }] },
      { label: 'Que se arregle solo/a', outcomes: [{ weight: 1, text: 'Le dijiste que era su problema. La confianza se rompió.', effects: [fx.close('target', -25), fx.hap(-3)] }] },
    ] },
  { id: 'rel.moving_in', title: 'Vivir juntos', tags: ['rel'], target: 'partner', weight: 9, once: true,
    conditions: [c.age(18, 60), c.tClose(55), c.single()],
    text: '{target} te propone mudarse juntos. Es un gran paso.',
    choices: [
      { label: 'Aceptar', outcomes: [
        { weight: 7, text: 'Se mudaron juntos. Descubriste que {target} deja los platos sucios.', effects: [fx.close('target', 8), fx.hap(4), fx.flag('cohabiting')] },
        { weight: 3, text: 'La convivencia fue más difícil de lo pensado.', effects: [fx.close('target', -8), fx.hap(-2), fx.flag('cohabiting')] },
      ] },
      { label: 'Decir que todavía no', outcomes: [{ weight: 1, text: '{target} lo tomó a mal, aunque dijo que entendía.', effects: [fx.close('target', -8)] }] },
    ] },
  { id: 'rel.in_laws', title: 'Los suegros', tags: ['rel'], target: 'partner', weight: 6,
    conditions: [c.married(), c.age(22, 70)],
    text: 'Pasaste las fiestas con los padres de {target}. Te preguntaron cuándo van a tener hijos. Otra vez.',
    effects: [fx.hap(-3)] },
  { id: 'rel.sibling_rivalry', title: 'Rivalidad', tags: ['rel'], target: 'sibling', weight: 7,
    conditions: [c.age(10, 90)],
    text: '{target} y vos discutieron por la herencia de un mueble. Un mueble.',
    effects: [fx.close('target', -10), fx.hap(-2)] },
  { id: 'rel.sibling_wedding', title: 'Casamiento de {target}', tags: ['rel'], target: 'sibling', weight: 6,
    conditions: [c.age(22, 60), c.tAge(22)],
    text: '{target} se casa. Sos parte de la comitiva y llorás más que los novios.',
    effects: [fx.close('target', 10), fx.hap(5), fx.money(-400)] },
  { id: 'rel.mother_visit', title: 'Visita a tu mamá', tags: ['rel'], target: 'mother', weight: 8,
    conditions: [c.age(25, 90), c.tAge(50)],
    text: '{target} te pide que la visites. Hace tiempo que no se ven.',
    choices: [
      { label: 'Visitarla', outcomes: [{ weight: 1, text: 'Pasaron la tarde con mates y fotos viejas. {target} estaba feliz.', effects: [fx.close('target', 14), fx.hap(4)] }] },
      { label: 'Excusarte', outcomes: [{ weight: 1, text: 'Le dijiste que estabas ocupado. Se quedó mirando el teléfono.', effects: [fx.close('target', -12), fx.hap(-3)] }] },
    ] },
  { id: 'rel.father_health', title: 'Tu papá se opera', tags: ['rel'], target: 'father', weight: 6,
    conditions: [c.age(30, 90), c.tAge(55)],
    text: '{target} necesita una operación y te pidió que lo acompañes.',
    choices: [
      { label: 'Acompañarlo', outcomes: [{ weight: 1, text: 'Estuviste a su lado en el hospital. Salió todo bien.', effects: [fx.close('target', 15), fx.hap(2), fx.hea(-1)] }] },
      { label: 'No poder ir', outcomes: [{ weight: 1, text: 'Te quedaste trabajando. Lo vas a lamentar.', effects: [fx.close('target', -15), fx.hap(-4)] }] },
    ] },
  { id: 'rel.child_first_steps', title: 'Primeros pasos', tags: ['rel'], target: 'child', weight: 12,
    conditions: [c.tAge(1, 2)],
    text: '{target} dio sus primeros pasos, directo hacia vos. Te lo perdiste por mirar el celular, pero fingiste que no.',
    effects: [fx.close('target', 6), fx.hap(6)] },
  { id: 'rel.child_award', title: 'Premio escolar', tags: ['rel'], target: 'child', weight: 8,
    conditions: [c.tAge(6, 17)],
    text: '{target} ganó un premio en la escuela. Sacaste 200 fotos y las mandaste a toda la familia.',
    effects: [fx.close('target', 6), fx.hap(5)] },
  { id: 'rel.child_rebel', title: 'Rebeldía', tags: ['rel'], target: 'child', weight: 8,
    conditions: [c.tAge(13, 17)],
    text: '{target} llegó a las 5 de la mañana oliendo a algo que no era jugo de manzana.',
    choices: [
      { label: 'Confrontarlo/a', outcomes: [
        { weight: 5, text: 'Hablaron a los gritos. Se sinceró y prometió cuidarse.', effects: [fx.close('target', 4)] },
        { weight: 5, text: '{target} se fue de casa dando un portazo. Volvió a los dos días.', effects: [fx.close('target', -15), fx.hap(-5)] },
      ] },
      { label: 'Hacer la vista gorda', outcomes: [{ weight: 1, text: 'No dijiste nada. Ya veremos cómo termina.', effects: [fx.close('target', -3), fx.hap(-2)] }] },
    ] },
  { id: 'rel.child_moves_out', title: 'Se independiza', tags: ['rel'], target: 'child', weight: 6,
    conditions: [c.tAge(20, 40)],
    text: '{target} se fue a vivir solo/a. La casa quedó muy silenciosa, aunque la heladera está más llena.',
    effects: [fx.hap(-2), fx.close('target', 3)] },
  { id: 'rel.ex_gossip', title: 'Chismes', tags: ['rel'], target: 'ex', weight: 6,
    conditions: [c.age(18, 80)],
    text: 'Te enterás de que {target} anda diciendo cosas horribles de vos. La mayoría son mentiras. La mayoría.',
    effects: [fx.hap(-4)] },
];
